### ISSUE TITLE
Is VHOST required in the app directory?

### ISSUE THREAD

**Issue by henry74** [mikexstudios/dokku-nginx-alt#14]
I'd like dokku to continue autogenerating the URL based on appname.  Currently without VHOST, there is no URL when it was auto generated before.  I like the ability to specify my own nginx file, but still want to keep the url generation...is this possible?

**Comment by mikexstudios** [comment]
No... but this was intentional. I wanted this plugin to only read from VHOST and not write to it in any way. My original plan was to separate the autogeneration of subdomains into a separate plugin: https://github.com/mikexstudios/dokku/tree/subdomain2/plugins/auto-subdomains, but that pull request languished in the main dokku repo. If you like, I can put that plugin in its own git repo.
